### ISSUE TITLE
03.01.01 Part 3 - view personal profile

### ISSUE THREAD

**Issue by EPostill** [CMPUT301F19T02/Vybe#44] opened 2019-10-13 23:25 UTC
As a participant, I want to be able to view my profile, so I can see the details of my profile

Story Points: 5

#16

Task List
- [ ] Create xml for viewing profile
- [ ] grab profile info from database
- [ ] insert profile info to be viewed by user

**Comment by TheBroMoe** [comment] 2019-11-13 23:35
This issue is a duplicate of Issue #42 so now closing

**Closed by TheBroMoe** 2019-11-13 23:35 UTC
Labels: Medium Risk
